{{- if and .Values.extraCertificates.enabled (not .Values.extraCertificates.configMapName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heimdall.fullname" . }}-ca-certs
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.extraCertificates.certificates }}
  {{ $filename }}: |
{{ $content | indent 4 }}
  {{- end }}
{{- end }}
