{{- if (.Values.heimdall.ingress).enabled -}}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- $fullName := include "heimdall.fullname" . -}}
apiVersion: {{.Values.heimdall.ingress.apiVersion}}
kind: {{ .Values.heimdall.ingress.kind }}
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
  {{- with .Values.heimdall.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.heimdall.ingress.tls }}
  tls:
  {{- range .Values.heimdall.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  {{- if and .Values.heimdall.ingress.className (semverCompare ">=1.18-0" $kubeVersion) }}
  ingressClassName: {{ .Values.heimdall.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.heimdall.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
        {{- end }}
  {{- end }}
{{- end }}